# Generated by Django 3.2.20 on 2023-09-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneralConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="The logo that will be displayed in the frontend.",
                        upload_to="logo/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="The favicon that will be displayed in the browser tabs.",
                        upload_to="logo/",
                        verbose_name="favicon",
                    ),
                ),
                (
                    "openzaak_admin_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL of the Open Zaak admin. A link is shown to the users if they want to perform actions that are not possible via Open Zaaktypebeheer.",
                        max_length=1000,
                        verbose_name="openzaak admin URL",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
