# Generated by Django 3.2.20 on 2023-09-05 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalconfiguration",
            name="theme_class_name",
            field=models.SlugField(
                blank=True,
                help_text="If provided, this class name will be set on the <html> element.",
                verbose_name="theme class name",
            ),
        ),
        migrations.AddField(
            model_name="generalconfiguration",
            name="theme_stylesheet",
            field=models.FileField(
                blank=True,
                help_text="A stylesheet with theme-specific css. ",
                upload_to="config/themes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("css",)
                    )
                ],
                verbose_name="theme stylesheet",
            ),
        ),
    ]
